SET storage_engine=InnoDB;

CREATE TABLE PESSOAS(
	URI VARCHAR(100) NOT NULL,
	CIDADE_NATAL VARCHAR(40) NULL,
	NOME_COMPLETO VARCHAR(50) NOT NULL,
	PRIMARY KEY(URI)
);

CREATE TABLE TIPO_BLOQUEIO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE RELACAO(
	USUARIO VARCHAR(100) NOT NULL,
	PESSOA_ALVO VARCHAR(100) NOT NULL,
	TIPO_BLOQUEIO INTEGER NULL,
	DESCRICAO VARCHAR(150) NULL,
	PRIMARY KEY(USUARIO,PESSOA_ALVO,TIPO_BLOQUEIO),
	FOREIGN KEY(USUARIO)
		REFERENCES PESSOAS(URI)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	FOREIGN KEY(PESSOA_ALVO)
		REFERENCES PESSOAS(URI)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	FOREIGN KEY(TIPO_BLOQUEIO)
		REFERENCES TIPO_BLOQUEIO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);

CREATE TABLE ARTISTAS_MUSICAIS(
	URI VARCHAR(100) NOT NULL,
	PAIS VARCHAR(40) NOT NULL,
	GENERO VARCHAR(40) NOT NULL,
	NOME_ARTISTICO VARCHAR(40) NOT NULL,
	PRIMARY KEY(URI)
);

CREATE TABLE CANTORES(
	CODIGO VARCHAR(100) NOT NULL,
	PRIMARY KEY(CODIGO),
	FOREIGN KEY(CODIGO)
		REFERENCES ARTISTAS_MUSICAIS(URI)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE BANDAS(
	CODIGO VARCHAR(100) NOT NULL,
	PRIMARY KEY(CODIGO),
	FOREIGN KEY(CODIGO)
		REFERENCES ARTISTAS_MUSICAIS(URI)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE MUSICOS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ESTILO_MUSICAL VARCHAR(40) NOT NULL,
	DATA_NASCIMENTO DATE NULL,
	NOME_REAL VARCHAR(50) NULL,
	CANTOR VARCHAR(100) NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CANTOR)
		REFERENCES CANTORES(CODIGO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);

CREATE TABLE INTEGRANTES_BANDAS(
	BANDA VARCHAR(100) NOT NULL,
	MUSICO INTEGER NOT NULL,
	PRIMARY KEY(BANDA,MUSICO),
	FOREIGN KEY(BANDA)
		REFERENCES BANDAS(CODIGO)
		ON DELETE CASCADE
		ON UPDATE NO ACTION,
	FOREIGN KEY(MUSICO)
		REFERENCES MUSICOS(ID)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE AVALIACOES(
	USUARIO VARCHAR(100) NOT NULL,
	ARTISTA VARCHAR(100) NOT NULL,
	NOTA INTEGER NOT NULL,
	PRIMARY KEY(USUARIO,ARTISTA),
	FOREIGN KEY(USUARIO)
		REFERENCES PESSOAS(URI)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(ARTISTA)
		REFERENCES ARTISTAS_MUSICAIS(URI)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);
INSERT INTO TIPO_BLOQUEIO (ID, TIPO) VALUES (1, "Sem bloqueio");