#!/bin/bash
FOLDER_TEST="testes"
DISCIPLINA="mc558a"
LAB="p5"
for i in `seq 0 6`;
do
	echo -e "Teste $i: "
	curl "https://susy.ic.unicamp.br:9999/$DISCIPLINA/$LAB/dados/arq$i.in" --insecure > "$FOLDER_TEST/arq$i.in"
	curl "https://susy.ic.unicamp.br:9999/$DISCIPLINA/$LAB/dados/arq$i.res" --insecure > "$FOLDER_TEST/arq$i.res"
	echo " ----------------------------------- "
done
